### ISSUE TITLE
to-do list fwildclusterboot 0.8

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/fwildclusterboot#33]
- [x] add safe `to_integer` functions that turns characters into integers
- [x] update pkgdown
- [x] update vignette
- [x] update readme; update benchmarks
- [x] update description file
- [x] update examples for `waldboottest()` methods
- [x] update examples for `ivreg` method
- [x] write and add `JuliaConnectoR.utils` package
- [x] fix t-stat tests
- [x] write reproducible error message for WRE with two-way clustering
- [x] #37
- [x] add support for 'lean' rcpp based algorithms
- [x] fix seeding for rcpp based algorithms
- [x] rename function argument `beta0` to `r`, write deprecation note
- [x] add a global variable option to set `boot_algo = "WildBootTests.jl"` for all calls of `boottest()`
- [x] switch to Float64 by default
- [x] fix bugs in `tidy()` and `summary` methods when `boot_algo = WildBootTests.jl`
- [x] fix methods for objects of type `waldboottest`
- [x] fix methods for objects of type `boottest` when `boot_algo = "WildBootTests.jl"`
- [x] update based on changes in WildBootTests 0.7.7 https://github.com/droodman/WildBootTests.jl/issues/10
- [x] fix `set_julia_seed()` function
- [x] #40
- [x] rename `waldboottest()` to `multboottest`
- [x] rename test statistic result in ``waldboottest()` - currently, it is returned as `t_stat` -> misleading
- [x] clean up function pre-processing
- [x] write dedicated test suite for subcluster bootstrap
- [ ] #34
- [ ] review documentation
- [ ] add description of unit tests

The following features are moved to a later version: 

- [ ] submit `JuliaConnectoR.utils` to CRAN - else it can't be in suggests
- [ ] add methods for `plm::plm()` (except for random effects models)
- [ ] update `warning_error_tests` regarding added `WildBootTests.jl` functionality

**Comment by s3alfisc** [comment]
close as fwildclusterboot 0.8 submitted to CRAN
